export let courses = [
    {
        id: 1,
        category: "Information Technology",
        name: "Introduction to Computer Science",
        provider: "EDX",
        duration: "10 Hours per day",
        price: "Free",
        image: "https://ccitraining.edu/wp-content/uploads/2023/12/Information-Technology.jpg",
        link: "https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science",
     },
     {
        id: 2,
        category: "Information Technology",
        name: "Introduction to Cyber Security",
        provider: "Udemy",
        duration: "1 Hours per day",
        price: "Free",
        image: "https://static.vecteezy.com/system/resources/thumbnails/006/950/568/small_2x/cyber-security-data-protection-business-concept-on-virtual-screen-shield-protect-icon-in-wireframe-robotic-hand-antivirus-interface-illustration-vector.jpg",
        link: "https://www.udemy.com/course/certified-secure-netizen/",
     },
    {
        id: 3,
        category: "Information Technology",
        name: "Web Development Basics",
        provider: "EDX",
        duration: "1 Hours per day",
        price: "Free",
        image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        link: "https://www.edx.org/learn/computer-science/ibm-guided-project-web-development-w-html-css-for-beginners?index=product&queryID=d3b7fadf8901acea3dc60500ccb88b8e&position=2&results_level=first-level-results&term=Web+Development+Basics&objectID=course-40eabb04-17b3-430d-85e8-3f2ef697417e&campaign=Guided+Project%3A+Web+Development+w%2F+HTML+%26+CSS+for+Beginners&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 4,
        category: "Information Technology",
        name: "4.Google IT Automation with Python",
        provider: "Udemy",
        duration: "2 Hours per day",
        price: "Paid",
        image: "https://fabiopacifici.com/wp-content/uploads/2020/02/Learn_python_with_google_image.jpg",
        link: "https://www.udemy.com/course/python-from-beginner-to-expert-starter-free/",
     },
     {
        id: 5,
        category: "Business",
        name: "Entrepreneurship in Emerging Economies",
        provider: "EDX",
        duration: "18 Hours per day",
        price: "Paid",
        image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        link: "https://www.edx.org/learn/entrepreneurship/harvard-university-entrepreneurship-in-emerging-economies?index=product&queryID=21417bef07b01d1e4db67bdf56f80eee&position=4&linked_from=autocomplete&c=autocomplete",
     },
     {
        id: 6,
        category: "Business",
        name: "Innovation for Entrepreneurs",
        provider: "Udemy",
        duration: "1 Hours per day",
        price: "Free",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVVLqGASMUSkTAdxM10lNP1QXEqxpsX6U1hw&s",
        link: "https://www.udemy.com/course/60-day-startup-introduction-to-startups/",
     },
     {
        id: 7,
        category: "Business",
        name: "Fundamentals of Digital Marketing",
        provider: "Udemy",
        duration: "1 Hours per day",
        price: "Free",
        image: "https://www.springboard.com/blog/wp-content/uploads/2022/06/what-is-digital-marketing.png",
        link: "https://www.udemy.com/course/the-fundamentals-of-the-digital-marketing/",
     },
     {
        id: 8,
        category: "Business",
        name: "Business Fundamentals",
        provider: "EDX",
        duration: "18 Hours per day",
        price: "Free",
        image: "https://online.hbs.edu/Style%20Library/api/resize.aspx?imgpath=/PublishingImages/Business%20Fundamentals.jpg&w=1200&h=630",
        link: "https://www.edx.org/learn/Business-administration/university-of-british-columbia-Business-foundations?index=product&queryID=391d5f0e1c09959a429b133c779c9890&position=1&results_level=first-level-results&term=Business+fundamentals&objectID=course-1c30e9b3-78ee-4c57-9af9-922153073d99&campaign=Business+Foundations&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 9,
        category: "Healthcare",
        name: "Introduction to Psychology",
        provider: "EDX",
        duration: "50 Hours Total",
        price: "Free",
        image: "https://blogs.longwood.edu/edwinelleportfolio/files/2016/12/blog-examprep-061913.jpg",
        link: "https://www.edx.org/learn/python/st-margarets-episcopal-school-introduction-to-psychology?index=product&queryID=8f57a3b8e1f080ee7583bb6dcd9566f3&position=2&results_level=first-level-results&term=introduction+to+pyschology&objectID=course-1580c6c4-5a81-4a79-bf35-bb4dddfb891f&campaign=Introduction+to+Psychology&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     { 
        id: 10,
        category: "Healthcare",
        name: "COVID-19: Tackling the Novel Coronavirus",
        provider: "Udemy",
        duration: "2 Hours per day",
        price: "Free",
        image: "https://www.statnews.com/wp-content/uploads/2020/02/Coronavirus-CDC-645x645.jpg",
        link: "https://www.udemy.com/course/mental-health-for-coping-with-stress-anxiety-covid-19/",
     },
     {
        id: 11,
        category: "Healthcare",
        name: "Health Informatics on FHIR",
        provider: "EDX",
        duration: "50 Hours",
        price: "Paid",
        image: "https://www.onyxhealth.io/wp-content/uploads/2021/02/fhir-1.png",
        link: "https://www.edx.org/learn/health-informatics/the-georgia-institute-of-technology-health-informatics-data-and-interoperability-standards?index=product&queryID=6c8de4b7d5aa6dc5c3480b7b6d1868d3&position=1&results_level=first-level-results&term=Health+Informatics+on+FHIR&objectID=course-e3933140-d4dc-4a6a-bf08-4e068cc5609e&campaign=Health+Informatics%3A+Data+and+Interoperability+Standards&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 12,
        category: "Healthcare",
        name: "Nutrition and Health: Macronutrients and Overnutrition",
        provider: "EDX",
        duration: "52 Hours",
        price: "Free",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2ACuGHpVzK7aiL7VtielvqPBgBgacxh9uUQ&s",
        link: "https://www.edx.org/learn/nutrition/wageningen-university-research-nutrition-and-health-macronutrients-and-overnutrition?index=product&queryID=3a8f18279511ec67a15e1d6d9c96bbca&position=1&results_level=first-level-results&term=Nutrition+and+Health%3A+Macronutrients+and+Overnutrition&objectID=course-c2f0c9cd-6577-4f38-8a31-56c8dd1cf2a4&campaign=Nutrition+and+Health%3A+Macronutrients+and+Overnutrition&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 13,
        category: "Art",
        name: "Modern Art & Ideas",
        provider: "Udemy",
        duration: "1 Hour",
        price: "Free",
        image: "https://cdn.mos.cms.futurecdn.net/7YrobQvFFzw8aWsAUtoYXB-650-80.jpg.webp",
        link: "https://www.udemy.com/course/art-fundamentals-in-one-hour/",
     },
     {
        id: 14,
        category: "Art",
        name: "Shakespeares Life and Work",
        provider: "EDX",
        duration: "20 Hours",
        price: "Paid",
        image: "https://cdn.thecollector.com/wp-content/uploads/2024/08/top-plays-william-shakespeare.jpg?width=1400&quality=70",
        link: "https://www.edx.org/learn/shakespeare/harvard-university-shakespeare-s-life-and-work?index=product&queryID=79c2392a4919e70fb6d143d3345533ce&position=1&results_level=first-level-results&term=Shakespeare%E2%80%99s+Life+and+Work&objectID=course-36eb1cb5-abab-4f1c-b9f7-1c386f5b11e7&campaign=Shakespeare%27s+Life+and+Work&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 15,
        category: "Art",
        name: "Introduction to Philosophy",
        provider: "Udemy",
        duration: "1 Hour",
        price: "Free",
        image: "https://philosophyawayoflife.com/wp-content/uploads/2021/10/philosophy-a-way-of-life-ph.jpg?w=1000",
        link: "https://www.udemy.com/course/introduction-to-philosophy-with-plato/",
     },
     {
        id: 16,
        category: "Art",
        name: "Film, Images & Historical Interpretation",
        provider: "Udemy",
        duration: "5 Hours",
        price: "Free",
        image: "https://www.thoughtco.com/thmb/LSSFSX6XnWWvyJieTJ_Vk_INrqE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-654313960-5c532556c9e77c00014b0273.jpg",
        link: "https://www.udemy.com/course/filmschoolcinema101/",
     },
     {
        id: 17,
        category: "Evs",
        name: "The Science of Climate Change",
        provider: "EDX",
        duration: "16 Hour",
        price: "Paid",
        image: "https://d2jx2rerrg6sh3.cloudfront.net/image-handler/ts/20211112073341/ri/673/picture/2021/11/shutterstock_1127223938.jpg",
        link: "https://www.edx.org/learn/climate-change/sdg-academy-climate-change-the-science-and-global-impact?index=product&queryID=e7325c8c18588dcef7ff21cbeaa01beb&position=1&results_level=first-level-results&term=Climate+Change&objectID=course-32779451-9094-45c8-9805-505bfe77ae02&campaign=Climate+Change%3A+The+Science+and+Global+Impact&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 18,
        category: "Evs",
        name: "Biodiversity and Conservation",
        provider: "EDX",
        duration: "7 Hours",
        price: "Free",
        image: "https://www.euroschoolindia.com/wp-content/uploads/2024/02/What-is-Biodiversity-Importance-Ways-To-Conserve.jpg",
        link: "https://www.edx.org/learn/ecosystems/ethx-environmental-dna-sensing-the-diversity-of-life-and-assessing-ecosystem-health?index=product&queryID=086404033b906d96cc0eb17afc3ac5a3&position=1&results_level=first-level-results&term=Biodiversity+and+Conservation&objectID=course-66aff7f5-721e-496e-9e85-4c62ded67880&campaign=Environmental+DNA%3A+Sensing+the+Diversity+of+Life+and+Assessing+Ecosystem+Health&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 19,
        category: "Evs",
        name: "Introduction to Environmental Law and Policy",
        provider: "EDX",
        duration: "5 Hour",
        price: "Free",
        image: "https://images.unsplash.com/photo-1467579424161-6bbc141569d7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        link: "https://www.edx.org/learn/climate-change/massachusetts-institute-of-technology-cities-and-climate-change-mitigation-and-adaptation?index=product&queryID=ab7f2c0e7b9545c7d914b57028209602&position=1&results_level=first-level-results&term=Environmental+Law+and+Policy&objectID=course-6101ee5b-bd7a-4ce0-b229-949de6bf28dd&campaign=Cities+and+Climate+Change%3A+Mitigation+and+Adaptation&source=edX&product_category=course&placement_url=https%3A%2F%2Fwww.edx.org%2Fsearch",
     },
     {
        id: 20,
        category: "Evs",
        name: "Global Environmental Management",
        provider: "Futurel",
        duration: "4 Hours",
        price: "Free",
        image: "https://media.istockphoto.com/id/1413930025/photo/crystal-globe-putting-on-moss-esg-icon-for-environment-social-and-governance.jpg?s=612x612&w=0&k=20&c=AfK7HKFtO8yy6JE557Agw6GJXojjMJWlH2lrGM_RD2o=",
        link: "https://www.futurelearn.com/courses/introduction-to-environmental-science",
     },
    ]
